#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global user.email "gep13@gep13.co.uk"
  - git config --global user.name "Gary Ewan Park"

# clone directory
clone_folder: C:\projects\gep13-github-io

# environment variables
environment:
  FLICKR_API_KEY: 9d1103bc0e467306fc1057bec04deff1
  FLICKR_API_SECRET:
    secure: 4KG1DGSiopfF3pwYpmZUo/6s3+x341m8wegmIBxCHBQ=
  GithubUsername: gep13
  GithubPassword:
    secure: XSuLygmr83zEpWcXIXMXGocN0QbooLud1eIMA3mQWKkT9LAU4TyrijLBcJIo7bD7
  

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmd: bundle install
  - cmd: if not exist _deploy (git clone https://%GithubUsername%:%GithubPassword%@github.com/%GithubUsername%/%GithubUsername%.github.io.git _deploy)
  - cmd: cd _deploy
  - cmd: git checkout master
  - cmd: cd ..
  - cmd: rake gen_deploy
  
test: off
