#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global user.email "gep13@gep13.co.uk"
  - git config --global user.name "Gary Ewan Park"

# clone directory
clone_folder: C:\projects\gep13-github-io

# environment variables
environment:
  GithubUsername: gep13
  GithubPassword:
    secure: 8nkd45DMSjFqay9ejGL2Eww79jHZW93WsTbBB2qbLmnsYKbtWTukpcrhzOkg7Rou
  FLICKR_API_KEY:
    secure: 2XneCxLArk7iXtNvI5owP5KWrIeP8ijiPMLmz91sYcQ=
  FLICKR_SHARED_SECRET:
    secure: nl9vBj7kln1NveWzNLO/GVztGPF21UAPKnfpTjC5GTfFtBUd1SbOO+O/3rM0dYan
  FLICKR_ACCESS_TOKEN:
    secure: obdKLDvCO2Vszsv65fIDLg6YE6/QKbsAHU38Zz5jgQOnfen1MXuknnnqEB0y0XwB
  FLICKR_ACCESS_SECRET:
    secure: 4KG1DGSiopfF3pwYpmZUo/6s3+x341m8wegmIBxCHBQ=
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem
  - SET SSL_CERT_FILE=%APPVEYOR_BUILD_FOLDER%\cacert.pem
  
build_script:
  - cmd: gem install bundler
  - cmd: bundle install
  - cmd: set SSL_CERT_FILE=%CD%\flickr.pem
  - cmd: if not exist _deploy (git clone https://%GithubUsername%:%GithubPassword%@github.com/%GithubUsername%/%GithubUsername%.github.io.git _deploy)
  - cmd: cd _deploy
  - cmd: git checkout master
  - cmd: cd ..
  - cmd: rake generate
  - cmd: rake deploy
  
test: off

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/ 
  
#cache:
#  - C:\Ruby193\lib\ruby\gems\1.9.1
#  - C:\Ruby193\bin
